-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.contas_corrente
(
    id bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 ),
    id_cliente bigint NOT NULL,
    saldo numeric,
    limite numeric,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.enderecos
(
    id bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 ),
    cep character varying(9) NOT NULL,
    logradouro character varying(128) NOT NULL,
    numero character varying(32) NOT NULL,
    complemento character varying(128),
    bairro character varying(128) NOT NULL,
    cidade character varying(128) NOT NULL,
    uf character varying(2) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.clientes
(
    id bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 ),
    id_endereco bigint NOT NULL,
    nome character varying(128) NOT NULL,
    sobrenome character varying(128) NOT NULL,
    cpf character varying(11) NOT NULL,
    data_nascimento date NOT NULL,
    PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.contas_corrente
    ADD CONSTRAINT fk_conta_cliente FOREIGN KEY (id_cliente)
    REFERENCES public.clientes (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.clientes
    ADD CONSTRAINT fk_cliente_endereco FOREIGN KEY (id_endereco)
    REFERENCES public.enderecos (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;